# Input and Output

In [1]:
import numpy as np

## NumPy binary files (NPY)

Q1. Save x into `temp.npy` and load it.

In [5]:
x = np.arange(10)
...

# Check if there exists the 'temp.npy' file.
import os
if os.path.exists('temp.npy'):
    x2 = ...
    print(np.array_equal(x, x2))


True


## Text files

Q3. Save x to 'temp.txt' in string format and load it.

In [7]:
x = np.arange(10).reshape(2, 5)
header = 'num1 num2 num3 num4 num5'
...
...

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.]])

Q4. Save `x`, `y`, and `z` to 'temp.txt' in string format line by line, then load it.

In [8]:
x = np.arange(10)
y = np.arange(11, 21)
z = np.arange(22, 32)
...
...

array([[  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.],
       [ 11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.],
       [ 22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.]])

Q5. Convert `x` into bytes, and load it as array.

In [9]:
x = np.array([1, 2, 3, 4])
x_bytes = ...
x2 = ...
print(np.array_equal(x, x2))


True


Q6. Convert `a` into an ndarray and then convert it into a list again.

In [10]:
a = [[1, 2], [3, 4]]
x = ...
a2 = ...
print(a == a2)

True


## String formatting¶

Q7. Convert `x` to a string, and revert it.

In [11]:
x = np.arange(10).reshape(2,5)
x_str = ...
print(x_str, "\n", type(x_str))
x_str = x_str.replace("[", "") # [] must be stripped
x_str = x_str.replace("]", "")
x2 = ...
assert np.array_equal(x, x2)



[[0 1 2 3 4]
 [5 6 7 8 9]] 
 <class 'str'>
