# Input and Output

In [1]:
import numpy as np

## NumPy binary files (NPY)

Q1. Save x into `temp.npy` and load it.

In [2]:
x = np.arange(10)
...

# Check if there exists the 'temp.npy' file.
import os
if os.path.exists('temp.npy'):
    x2 = np.load('temp.py')
    print(np.array_equal(x, x2))


## Text files

Q3. Save x to 'temp.txt' in string format and load it.

In [8]:
x = np.arange(10).reshape(2, 5)
header = 'num1 num2 num3 num4 num5'
np.savetxt('temp.txt', x, fmt="%d", header=header)
np.loadtxt('temp.txt')

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

Q4. Save `x`, `y`, and `z` to 'temp.txt' in string format line by line, then load it.

In [12]:
x = np.arange(10)
y = np.arange(11, 21)
z = np.arange(22, 32)

p = np.array([x,y,z])
np.savetxt('temp.txt', p)

np.loadtxt('temp.txt')

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [11., 12., 13., 14., 15., 16., 17., 18., 19., 20.],
       [22., 23., 24., 25., 26., 27., 28., 29., 30., 31.]])

Q5. Convert `x` into bytes, and load it as array.

In [13]:
x = np.array([1, 2, 3, 4])
x_bytes = x.tobytes()
x2 = np.frombuffer(x_bytes, dtype=x.dtype)
print(np.array_equal(x, x2))


True


Q6. Convert `a` into an ndarray and then convert it into a list again.

In [31]:
a = [[1, 2], [3, 4]]
x = np.array(a)
a2 = x.tolist()
print(a == a2)

True


## String formatting¶

Q7. Convert `x` to a string, and revert it.

In [25]:
x = np.arange(10).reshape(2,5)
print(x)
x_str = np.array_str(x)
print(x_str, "\n", type(x_str))
x_str = x_str.replace("[", "") # [] must be stripped
x_str = x_str.replace("]", "")
print(x_str)


x2 = np.array([x_str])
print(x2)

# I could not do the Revert part properly

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]] 
 <class 'str'>
0 1 2 3 4
 5 6 7 8 9
['0 1 2 3 4\n 5 6 7 8 9']
