In [2]:
import numpy as np
x = np.arange(10)
np.save('temp.npy',x)
import os
if os.path.exists('temp.npy'):
    x2 = np.load('temp.npy')
    print(np.array_equal(x, x2))

True


In [2]:
import numpy as np
x = np.arange(10).reshape(2, 5)
Header = 'num1 num2 num3 num4 num5'
np.savetxt('temp.txt',x,fmt = '%d',header = Header)#saves the file in text format array in decimal
y=np.genfromtxt('temp.txt')
print(y)

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]


In [3]:
x = np.arange(10)
y = np.arange(11, 21)
z = np.arange(22, 32)

data = np.array([x,y,z]) 
np.savetxt('temp.txt',data)

y=np.loadtxt('temp.txt')
print(y)
#x,y,z are stored in data & save it to temp.txt,load it to y 

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]
 [22. 23. 24. 25. 26. 27. 28. 29. 30. 31.]]


In [4]:
x = np.array([1, 2, 3, 4])
x_bytes = x.tobytes()
x2 = np.frombuffer(x_bytes,dtype = x.dtype)
print(np.array_equal(x, x2))
#converting x in bytes using to bytes and comparing 

True


In [5]:
a = [[1, 2], [3, 4]]
x = np.array(a) 
a2 = x.tolist() 
print(a == a2)
#converting to numpy array then again to list
#& comparing

True
