# Assignment - 4

In [1]:
import numpy as np

1. Create a new array of 2*2 integers, without initializing entries.


In [2]:
np.ones((2,2), dtype = "int")

array([[1, 1],
       [1, 1]])

2.Let X = np.array([1,2,3], [4,5,6], np.int32). Create a new array with the same shape and type as X.

In [4]:
X = np.array(([1,2,3], [4,5,6]), np.int32)
np.ones_like(X)

array([[1, 1, 1],
       [1, 1, 1]])

3.Create a 3-D array with ones on the diagonal and zeros elsewhere.

In [5]:
np.diag(np.ones(3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

4.Create a new array of 3*2 float numbers, filled with ones.

In [6]:
np.ones((3,2), dtype = "float")

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

5.Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [7]:
x = np.arange(4, dtype=np.int64)
np.ones_like(x)

array([1, 1, 1, 1], dtype=int64)

6.Create a new array of 3*2 float numbers, filled with zeros

In [8]:
np.zeros((3,2), dtype = "float")

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

7.Let x = np.arange(4, dtype=np.int64). Create an array of zeros with the same shape and type as X.

In [9]:
x = np.arange(4, dtype=np.int64)
np.zeros_like(x)

array([0, 0, 0, 0], dtype=int64)

8.Create a new array of 2*5 uints, filled with 6.

In [10]:
np.full((2,5),6)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

9.Let x = np.arange(4, dtype=np.int64). Create an array of 6's with the same shape and type as X.

In [11]:
x = np.arange(4, dtype=np.int64)
np.full_like(x, 6)

array([6, 6, 6, 6], dtype=int64)

10. Create an array of [1, 2, 3].

In [13]:
np.array((1,2,3))

array([1, 2, 3])

11.Let x = [1, 2]. Convert it into an array.

In [14]:
x = [1, 2]
np.array(x)

array([1, 2])

12.Let X = np.array([[1, 2], [3, 4]]). Convert it into a matrix.

In [15]:
X = np.array([[1, 2], [3, 4]])
X

array([[1, 2],
       [3, 4]])

13.Let x = [1, 2]. Conver it into an array of float.

In [16]:
x = [1,2]
np.array(x, dtype = "float")

array([1., 2.])

14.Let x = np.array([30]). Convert it into scalar of its single element, i.e. 30.

In [17]:
x = np.array([30])
np.asscalar(x)

30

15.Let x = np.array([1, 2, 3]). Create a array copy of x, which has a different id from x.

In [19]:
x = np.array([1, 2, 3])
y = x.copy()
print(id(x), x)
print(id(y), y)

2663187254208 [1 2 3]
2663187253568 [1 2 3]


16.Create an array of 2, 4, 6, 8, ..., 100.

In [20]:
np.arange(2,101,2)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

17.Create a 1-D array of 50 evenly spaced elements between 3. and 10., inclusive.

In [21]:
np.logspace(3,10,50)

array([1.00000000e+03, 1.38949549e+03, 1.93069773e+03, 2.68269580e+03,
       3.72759372e+03, 5.17947468e+03, 7.19685673e+03, 1.00000000e+04,
       1.38949549e+04, 1.93069773e+04, 2.68269580e+04, 3.72759372e+04,
       5.17947468e+04, 7.19685673e+04, 1.00000000e+05, 1.38949549e+05,
       1.93069773e+05, 2.68269580e+05, 3.72759372e+05, 5.17947468e+05,
       7.19685673e+05, 1.00000000e+06, 1.38949549e+06, 1.93069773e+06,
       2.68269580e+06, 3.72759372e+06, 5.17947468e+06, 7.19685673e+06,
       1.00000000e+07, 1.38949549e+07, 1.93069773e+07, 2.68269580e+07,
       3.72759372e+07, 5.17947468e+07, 7.19685673e+07, 1.00000000e+08,
       1.38949549e+08, 1.93069773e+08, 2.68269580e+08, 3.72759372e+08,
       5.17947468e+08, 7.19685673e+08, 1.00000000e+09, 1.38949549e+09,
       1.93069773e+09, 2.68269580e+09, 3.72759372e+09, 5.17947468e+09,
       7.19685673e+09, 1.00000000e+10])

18.Let X = np.array([[ 0, 1, 2, 3], [ 4, 5, 6, 7], [ 8, 9, 10, 11]]). Get the diagonal of X, that is, [0, 5, 10].

In [22]:
X = np.array([[ 0, 1, 2, 3], [ 4, 5, 6, 7], [ 8, 9, 10, 11]])
np.diag(X)

array([ 0,  5, 10])

19. Create a 2-D array whose diagonal equals [1, 2, 3, 4] and 0's elsewhere.

In [23]:
np.diagflat([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

20.Create an array which looks like below. array([[ 0., 0., 0., 0., 0.], [ 1., 0., 0., 0., 0.], [ 1., 1., 0., 0., 0.]])

In [28]:
np.tri(3,5,-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.]])

21.Create an array which looks like below. array([[ 0, 0, 0], [ 4, 0, 0], [ 7, 8, 0], [10, 11, 12]])

In [25]:
np.tril([[ 1,2,3], [4,5,6], [ 7, 8, 9], [10, 11, 12]], -1)

array([[ 0,  0,  0],
       [ 4,  0,  0],
       [ 7,  8,  0],
       [10, 11, 12]])

22.Create an array which looks like below. array([[ 1, 2, 3], [ 4, 5, 6], [ 0, 8, 9], [ 0, 0, 12]])

In [26]:
np.triu([[ 1,2,3], [4,5,6], [ 7, 8, 9], [10, 11, 12]], -1)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])