# Input and Output

In [1]:
import numpy as np

## NumPy binary files (NPY)

Q1. Save x into `temp.npy` and load it.

In [3]:
import numpy as np
x = np.arange(10)
np.save('temp',x)

# Check if there exists the 'temp.npy' file.
import os
if os.path.exists('temp.npy'):
    x2 = np.load('temp.npy')
    print(np.array_equal(x, x2))


True


## Text files

Q3. Save x to 'temp.txt' in string format and load it.

In [27]:
x = np.arange(10).reshape(2, 5)
Header = 'num1 num2 num3 num4 num5'
np.savetxt('temp.txt',x,fmt = '%d',header = Header)

y=np.genfromtxt('temp.txt')
print(y)


[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]


Q4. Save `x`, `y`, and `z` to 'temp.txt' in string format line by line, then load it.

In [35]:
x = np.arange(10)
y = np.arange(11, 21)
z = np.arange(22, 32)

data = np.array([x,y,z]) # container for the np arrays x,y and z
np.savetxt('temp.txt',data)

y=np.loadtxt('temp.txt')
print(y)

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]
 [22. 23. 24. 25. 26. 27. 28. 29. 30. 31.]]


Q5. Convert `x` into bytes, and load it as array.

In [52]:
x = np.array([1, 2, 3, 4])
x_bytes = x.tobytes() #converting to bytes
x2 = np.frombuffer(x_bytes,dtype = x.dtype)
print(np.array_equal(x, x2))

True


Q6. Convert `a` into an ndarray and then convert it into a list again.

In [64]:
a = [[1, 2], [3, 4]]
x = np.array(a) #converting to numpy array

a2 = x.tolist() # converting to list
print(a == a2)

True


## String formatting¶

Q7. Convert `x` to a string, and revert it.

In [138]:
x = np.arange(10).reshape(2,5)
x_str = np.array_str(x)


x_str = x_str.replace("[", "") # [] must be stripped
x_str = x_str.replace("]", "")
x_str = np.array(list(x_str)) # getting a list of chars 

# Reverting the Changes made to the original array

x2 = np.empty(shape = x.shape, dtype = x.dtype)
i=0
j=0
for char in x_str:   #converting the strings back to int and appending them to x2
    if char.isdigit() == True:
        int_ = char.astype(np.int)
        x2[i][j]=int_       
        j=j+1
        if j== x.shape[1]  and i < x.shape[0]: #controlling the shape of the array
            i=i+1
            j=0
            
print("x=",x)            
print("x2=",x2)
np.array_equal(x, x2)

x= [[0 1 2 3 4]
 [5 6 7 8 9]]
x2= [[0 1 2 3 4]
 [5 6 7 8 9]]


True

In [119]:
print(x.shape[0])

2
